/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminStandardsRouteImport } from './routes/admin.standards'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as AnalysisNewRouteImport } from './routes/analysis.new'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsIdRouteImport } from './routes/standards.$id'
import { Route as AnalysisIdReportRouteImport } from './routes/analysis.$id.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStandardsRoute = AdminStandardsRouteImport.update({
  id: '/admin/standards',
  path: '/admin/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisNewRoute = AnalysisNewRouteImport.update({
  id: '/analysis/new',
  path: '/analysis/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/standards/',
  path: '/standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIdRoute = StandardsIdRouteImport.update({
  id: '/standards/$id',
  path: '/standards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdReportRoute = AnalysisIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AnalysisIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/new': typeof AnalysisNewRoute
  '/standards/$id': typeof StandardsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/new': typeof AnalysisNewRoute
  '/standards/$id': typeof StandardsIdRoute
  '/admin': typeof AdminIndexRoute
  '/standards': typeof StandardsIndexRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/new': typeof AnalysisNewRoute
  '/standards/$id': typeof StandardsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/reports'
    | '/review'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/standards'
    | '/analysis/$id'
    | '/analysis/new'
    | '/standards/$id'
    | '/admin/'
    | '/standards/'
    | '/analysis/$id/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/reports'
    | '/review'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/standards'
    | '/analysis/$id'
    | '/analysis/new'
    | '/standards/$id'
    | '/admin'
    | '/standards'
    | '/analysis/$id/report'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/reports'
    | '/review'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/standards'
    | '/analysis/$id'
    | '/analysis/new'
    | '/standards/$id'
    | '/admin/'
    | '/standards/'
    | '/analysis/$id/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminStandardsRoute: typeof AdminStandardsRoute
  AnalysisIdRoute: typeof AnalysisIdRouteWithChildren
  AnalysisNewRoute: typeof AnalysisNewRoute
  StandardsIdRoute: typeof StandardsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/standards': {
      id: '/admin/standards'
      path: '/admin/standards'
      fullPath: '/admin/standards'
      preLoaderRoute: typeof AdminStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/new': {
      id: '/analysis/new'
      path: '/analysis/new'
      fullPath: '/analysis/new'
      preLoaderRoute: typeof AnalysisNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/': {
      id: '/standards/'
      path: '/standards'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$id': {
      id: '/standards/$id'
      path: '/standards/$id'
      fullPath: '/standards/$id'
      preLoaderRoute: typeof StandardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id/report': {
      id: '/analysis/$id/report'
      path: '/report'
      fullPath: '/analysis/$id/report'
      preLoaderRoute: typeof AnalysisIdReportRouteImport
      parentRoute: typeof AnalysisIdRoute
    }
  }
}

interface AnalysisIdRouteChildren {
  AnalysisIdReportRoute: typeof AnalysisIdReportRoute
}

const AnalysisIdRouteChildren: AnalysisIdRouteChildren = {
  AnalysisIdReportRoute: AnalysisIdReportRoute,
}

const AnalysisIdRouteWithChildren = AnalysisIdRoute._addFileChildren(
  AnalysisIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminStandardsRoute: AdminStandardsRoute,
  AnalysisIdRoute: AnalysisIdRouteWithChildren,
  AnalysisNewRoute: AnalysisNewRoute,
  StandardsIdRoute: StandardsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  StandardsIndexRoute: StandardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
