/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountPendingRouteImport } from './routes/account-pending'
import { Route as AccountRejectedRouteImport } from './routes/account-rejected'
import { Route as AccountSuspendedRouteImport } from './routes/account-suspended'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminStandardsRouteImport } from './routes/admin.standards'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as AnalysisNewRouteImport } from './routes/analysis.new'
import { Route as OfficerApplicationsRouteImport } from './routes/officer.applications'
import { Route as OfficerEvaluationRouteImport } from './routes/officer.evaluation'
import { Route as OfficerInspectionRouteImport } from './routes/officer.inspection'
import { Route as OfficerProcurementsRouteImport } from './routes/officer.procurements'
import { Route as OfficerProfileRouteImport } from './routes/officer.profile'
import { Route as OfficerVendorsRouteImport } from './routes/officer.vendors'
import { Route as ReviewerIndexRouteImport } from './routes/reviewer.index'
import { Route as ReviewerHistoryRouteImport } from './routes/reviewer.history'
import { Route as ReviewerProfileRouteImport } from './routes/reviewer.profile'
import { Route as ReviewerQueueRouteImport } from './routes/reviewer.queue'
import { Route as StandardsIndexRouteImport } from './routes/standards.index'
import { Route as StandardsIdRouteImport } from './routes/standards.$id'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorDocumentsRouteImport } from './routes/vendor.documents'
import { Route as VendorHistoryRouteImport } from './routes/vendor.history'
import { Route as VendorProcurementsRouteImport } from './routes/vendor.procurements'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorProfileRouteImport } from './routes/vendor.profile'
import { Route as AnalysisIdReportRouteImport } from './routes/analysis.$id.report'
import { Route as VendorApplicationsNewRouteImport } from './routes/vendor.applications.new'
import { Route as VendorAssessmentsIndexRouteImport } from './routes/vendor.assessments.index'
import { Route as VendorAssessmentsNewRouteImport } from './routes/vendor.assessments.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPendingRoute = AccountPendingRouteImport.update({
  id: '/account-pending',
  path: '/account-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRejectedRoute = AccountRejectedRouteImport.update({
  id: '/account-rejected',
  path: '/account-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSuspendedRoute = AccountSuspendedRouteImport.update({
  id: '/account-suspended',
  path: '/account-suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStandardsRoute = AdminStandardsRouteImport.update({
  id: '/admin/standards',
  path: '/admin/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisNewRoute = AnalysisNewRouteImport.update({
  id: '/analysis/new',
  path: '/analysis/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerApplicationsRoute = OfficerApplicationsRouteImport.update({
  id: '/officer/applications',
  path: '/officer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerEvaluationRoute = OfficerEvaluationRouteImport.update({
  id: '/officer/evaluation',
  path: '/officer/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerInspectionRoute = OfficerInspectionRouteImport.update({
  id: '/officer/inspection',
  path: '/officer/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerProcurementsRoute = OfficerProcurementsRouteImport.update({
  id: '/officer/procurements',
  path: '/officer/procurements',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerProfileRoute = OfficerProfileRouteImport.update({
  id: '/officer/profile',
  path: '/officer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerVendorsRoute = OfficerVendorsRouteImport.update({
  id: '/officer/vendors',
  path: '/officer/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerIndexRoute = ReviewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewerRoute,
} as any)
const ReviewerHistoryRoute = ReviewerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReviewerRoute,
} as any)
const ReviewerProfileRoute = ReviewerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ReviewerRoute,
} as any)
const ReviewerQueueRoute = ReviewerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ReviewerRoute,
} as any)
const StandardsIndexRoute = StandardsIndexRouteImport.update({
  id: '/standards/',
  path: '/standards/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsIdRoute = StandardsIdRouteImport.update({
  id: '/standards/$id',
  path: '/standards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorDocumentsRoute = VendorDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => VendorRoute,
} as any)
const VendorHistoryRoute = VendorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProcurementsRoute = VendorProcurementsRouteImport.update({
  id: '/procurements',
  path: '/procurements',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProfileRoute = VendorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VendorRoute,
} as any)
const AnalysisIdReportRoute = AnalysisIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AnalysisIdRoute,
} as any)
const VendorApplicationsNewRoute = VendorApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAssessmentsIndexRoute = VendorAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorAssessmentsNewRoute = VendorAssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => VendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-pending': typeof AccountPendingRoute
  '/account-rejected': typeof AccountRejectedRoute
  '/account-suspended': typeof AccountSuspendedRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/reviewer': typeof ReviewerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/new': typeof AnalysisNewRoute
  '/officer/applications': typeof OfficerApplicationsRoute
  '/officer/evaluation': typeof OfficerEvaluationRoute
  '/officer/inspection': typeof OfficerInspectionRoute
  '/officer/procurements': typeof OfficerProcurementsRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/vendors': typeof OfficerVendorsRoute
  '/reviewer/history': typeof ReviewerHistoryRoute
  '/reviewer/profile': typeof ReviewerProfileRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/standards/$id': typeof StandardsIdRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/history': typeof VendorHistoryRoute
  '/vendor/procurements': typeof VendorProcurementsRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
  '/vendor/applications/new': typeof VendorApplicationsNewRoute
  '/vendor/assessments/new': typeof VendorAssessmentsNewRoute
  '/vendor/assessments/': typeof VendorAssessmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-pending': typeof AccountPendingRoute
  '/account-rejected': typeof AccountRejectedRoute
  '/account-suspended': typeof AccountSuspendedRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/new': typeof AnalysisNewRoute
  '/officer/applications': typeof OfficerApplicationsRoute
  '/officer/evaluation': typeof OfficerEvaluationRoute
  '/officer/inspection': typeof OfficerInspectionRoute
  '/officer/procurements': typeof OfficerProcurementsRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/vendors': typeof OfficerVendorsRoute
  '/reviewer/history': typeof ReviewerHistoryRoute
  '/reviewer/profile': typeof ReviewerProfileRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/standards/$id': typeof StandardsIdRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/history': typeof VendorHistoryRoute
  '/vendor/procurements': typeof VendorProcurementsRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/admin': typeof AdminIndexRoute
  '/reviewer': typeof ReviewerIndexRoute
  '/standards': typeof StandardsIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
  '/vendor/applications/new': typeof VendorApplicationsNewRoute
  '/vendor/assessments/new': typeof VendorAssessmentsNewRoute
  '/vendor/assessments': typeof VendorAssessmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-pending': typeof AccountPendingRoute
  '/account-rejected': typeof AccountRejectedRoute
  '/account-suspended': typeof AccountSuspendedRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/reviewer': typeof ReviewerRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/vendor': typeof VendorRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/standards': typeof AdminStandardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/analysis/$id': typeof AnalysisIdRouteWithChildren
  '/analysis/new': typeof AnalysisNewRoute
  '/officer/applications': typeof OfficerApplicationsRoute
  '/officer/evaluation': typeof OfficerEvaluationRoute
  '/officer/inspection': typeof OfficerInspectionRoute
  '/officer/procurements': typeof OfficerProcurementsRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/vendors': typeof OfficerVendorsRoute
  '/reviewer/history': typeof ReviewerHistoryRoute
  '/reviewer/profile': typeof ReviewerProfileRoute
  '/reviewer/queue': typeof ReviewerQueueRoute
  '/standards/$id': typeof StandardsIdRoute
  '/vendor/documents': typeof VendorDocumentsRoute
  '/vendor/history': typeof VendorHistoryRoute
  '/vendor/procurements': typeof VendorProcurementsRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/profile': typeof VendorProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/standards/': typeof StandardsIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/analysis/$id/report': typeof AnalysisIdReportRoute
  '/vendor/applications/new': typeof VendorApplicationsNewRoute
  '/vendor/assessments/new': typeof VendorAssessmentsNewRoute
  '/vendor/assessments/': typeof VendorAssessmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-pending'
    | '/account-rejected'
    | '/account-suspended'
    | '/compare'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/reports'
    | '/review'
    | '/reviewer'
    | '/settings'
    | '/signup'
    | '/vendor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/profile'
    | '/admin/standards'
    | '/admin/users'
    | '/analysis/$id'
    | '/analysis/new'
    | '/officer/applications'
    | '/officer/evaluation'
    | '/officer/inspection'
    | '/officer/procurements'
    | '/officer/profile'
    | '/officer/vendors'
    | '/reviewer/history'
    | '/reviewer/profile'
    | '/reviewer/queue'
    | '/standards/$id'
    | '/vendor/documents'
    | '/vendor/history'
    | '/vendor/procurements'
    | '/vendor/products'
    | '/vendor/profile'
    | '/admin/'
    | '/reviewer/'
    | '/standards/'
    | '/vendor/'
    | '/analysis/$id/report'
    | '/vendor/applications/new'
    | '/vendor/assessments/new'
    | '/vendor/assessments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-pending'
    | '/account-rejected'
    | '/account-suspended'
    | '/compare'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/reports'
    | '/review'
    | '/settings'
    | '/signup'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/profile'
    | '/admin/standards'
    | '/admin/users'
    | '/analysis/$id'
    | '/analysis/new'
    | '/officer/applications'
    | '/officer/evaluation'
    | '/officer/inspection'
    | '/officer/procurements'
    | '/officer/profile'
    | '/officer/vendors'
    | '/reviewer/history'
    | '/reviewer/profile'
    | '/reviewer/queue'
    | '/standards/$id'
    | '/vendor/documents'
    | '/vendor/history'
    | '/vendor/procurements'
    | '/vendor/products'
    | '/vendor/profile'
    | '/admin'
    | '/reviewer'
    | '/standards'
    | '/vendor'
    | '/analysis/$id/report'
    | '/vendor/applications/new'
    | '/vendor/assessments/new'
    | '/vendor/assessments'
  id:
    | '__root__'
    | '/'
    | '/account-pending'
    | '/account-rejected'
    | '/account-suspended'
    | '/compare'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/reports'
    | '/review'
    | '/reviewer'
    | '/settings'
    | '/signup'
    | '/vendor'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/profile'
    | '/admin/standards'
    | '/admin/users'
    | '/analysis/$id'
    | '/analysis/new'
    | '/officer/applications'
    | '/officer/evaluation'
    | '/officer/inspection'
    | '/officer/procurements'
    | '/officer/profile'
    | '/officer/vendors'
    | '/reviewer/history'
    | '/reviewer/profile'
    | '/reviewer/queue'
    | '/standards/$id'
    | '/vendor/documents'
    | '/vendor/history'
    | '/vendor/procurements'
    | '/vendor/products'
    | '/vendor/profile'
    | '/admin/'
    | '/reviewer/'
    | '/standards/'
    | '/vendor/'
    | '/analysis/$id/report'
    | '/vendor/applications/new'
    | '/vendor/assessments/new'
    | '/vendor/assessments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountPendingRoute: typeof AccountPendingRoute
  AccountRejectedRoute: typeof AccountRejectedRoute
  AccountSuspendedRoute: typeof AccountSuspendedRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  ReviewerRoute: typeof ReviewerRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VendorRoute: typeof VendorRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminStandardsRoute: typeof AdminStandardsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AnalysisIdRoute: typeof AnalysisIdRouteWithChildren
  AnalysisNewRoute: typeof AnalysisNewRoute
  OfficerApplicationsRoute: typeof OfficerApplicationsRoute
  OfficerEvaluationRoute: typeof OfficerEvaluationRoute
  OfficerInspectionRoute: typeof OfficerInspectionRoute
  OfficerProcurementsRoute: typeof OfficerProcurementsRoute
  OfficerProfileRoute: typeof OfficerProfileRoute
  OfficerVendorsRoute: typeof OfficerVendorsRoute
  StandardsIdRoute: typeof StandardsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StandardsIndexRoute: typeof StandardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-pending': {
      id: '/account-pending'
      path: '/account-pending'
      fullPath: '/account-pending'
      preLoaderRoute: typeof AccountPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-rejected': {
      id: '/account-rejected'
      path: '/account-rejected'
      fullPath: '/account-rejected'
      preLoaderRoute: typeof AccountRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-suspended': {
      id: '/account-suspended'
      path: '/account-suspended'
      fullPath: '/account-suspended'
      preLoaderRoute: typeof AccountSuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/standards': {
      id: '/admin/standards'
      path: '/admin/standards'
      fullPath: '/admin/standards'
      preLoaderRoute: typeof AdminStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/new': {
      id: '/analysis/new'
      path: '/analysis/new'
      fullPath: '/analysis/new'
      preLoaderRoute: typeof AnalysisNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/applications': {
      id: '/officer/applications'
      path: '/officer/applications'
      fullPath: '/officer/applications'
      preLoaderRoute: typeof OfficerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/evaluation': {
      id: '/officer/evaluation'
      path: '/officer/evaluation'
      fullPath: '/officer/evaluation'
      preLoaderRoute: typeof OfficerEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/inspection': {
      id: '/officer/inspection'
      path: '/officer/inspection'
      fullPath: '/officer/inspection'
      preLoaderRoute: typeof OfficerInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/procurements': {
      id: '/officer/procurements'
      path: '/officer/procurements'
      fullPath: '/officer/procurements'
      preLoaderRoute: typeof OfficerProcurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/profile': {
      id: '/officer/profile'
      path: '/officer/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/vendors': {
      id: '/officer/vendors'
      path: '/officer/vendors'
      fullPath: '/officer/vendors'
      preLoaderRoute: typeof OfficerVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer/': {
      id: '/reviewer/'
      path: '/'
      fullPath: '/reviewer/'
      preLoaderRoute: typeof ReviewerIndexRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/history': {
      id: '/reviewer/history'
      path: '/history'
      fullPath: '/reviewer/history'
      preLoaderRoute: typeof ReviewerHistoryRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/profile': {
      id: '/reviewer/profile'
      path: '/profile'
      fullPath: '/reviewer/profile'
      preLoaderRoute: typeof ReviewerProfileRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/queue': {
      id: '/reviewer/queue'
      path: '/queue'
      fullPath: '/reviewer/queue'
      preLoaderRoute: typeof ReviewerQueueRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/standards/': {
      id: '/standards/'
      path: '/standards'
      fullPath: '/standards/'
      preLoaderRoute: typeof StandardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards/$id': {
      id: '/standards/$id'
      path: '/standards/$id'
      fullPath: '/standards/$id'
      preLoaderRoute: typeof StandardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/documents': {
      id: '/vendor/documents'
      path: '/documents'
      fullPath: '/vendor/documents'
      preLoaderRoute: typeof VendorDocumentsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/history': {
      id: '/vendor/history'
      path: '/history'
      fullPath: '/vendor/history'
      preLoaderRoute: typeof VendorHistoryRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/procurements': {
      id: '/vendor/procurements'
      path: '/procurements'
      fullPath: '/vendor/procurements'
      preLoaderRoute: typeof VendorProcurementsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/profile': {
      id: '/vendor/profile'
      path: '/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof VendorProfileRouteImport
      parentRoute: typeof VendorRoute
    }
    '/analysis/$id/report': {
      id: '/analysis/$id/report'
      path: '/report'
      fullPath: '/analysis/$id/report'
      preLoaderRoute: typeof AnalysisIdReportRouteImport
      parentRoute: typeof AnalysisIdRoute
    }
    '/vendor/applications/new': {
      id: '/vendor/applications/new'
      path: '/applications/new'
      fullPath: '/vendor/applications/new'
      preLoaderRoute: typeof VendorApplicationsNewRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/assessments/': {
      id: '/vendor/assessments/'
      path: '/assessments'
      fullPath: '/vendor/assessments/'
      preLoaderRoute: typeof VendorAssessmentsIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/assessments/new': {
      id: '/vendor/assessments/new'
      path: '/assessments/new'
      fullPath: '/vendor/assessments/new'
      preLoaderRoute: typeof VendorAssessmentsNewRouteImport
      parentRoute: typeof VendorRoute
    }
  }
}

interface ReviewerRouteChildren {
  ReviewerHistoryRoute: typeof ReviewerHistoryRoute
  ReviewerProfileRoute: typeof ReviewerProfileRoute
  ReviewerQueueRoute: typeof ReviewerQueueRoute
  ReviewerIndexRoute: typeof ReviewerIndexRoute
}

const ReviewerRouteChildren: ReviewerRouteChildren = {
  ReviewerHistoryRoute: ReviewerHistoryRoute,
  ReviewerProfileRoute: ReviewerProfileRoute,
  ReviewerQueueRoute: ReviewerQueueRoute,
  ReviewerIndexRoute: ReviewerIndexRoute,
}

const ReviewerRouteWithChildren = ReviewerRoute._addFileChildren(
  ReviewerRouteChildren,
)

interface VendorRouteChildren {
  VendorDocumentsRoute: typeof VendorDocumentsRoute
  VendorHistoryRoute: typeof VendorHistoryRoute
  VendorProcurementsRoute: typeof VendorProcurementsRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorProfileRoute: typeof VendorProfileRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorApplicationsNewRoute: typeof VendorApplicationsNewRoute
  VendorAssessmentsNewRoute: typeof VendorAssessmentsNewRoute
  VendorAssessmentsIndexRoute: typeof VendorAssessmentsIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorDocumentsRoute: VendorDocumentsRoute,
  VendorHistoryRoute: VendorHistoryRoute,
  VendorProcurementsRoute: VendorProcurementsRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorProfileRoute: VendorProfileRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorApplicationsNewRoute: VendorApplicationsNewRoute,
  VendorAssessmentsNewRoute: VendorAssessmentsNewRoute,
  VendorAssessmentsIndexRoute: VendorAssessmentsIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

interface AnalysisIdRouteChildren {
  AnalysisIdReportRoute: typeof AnalysisIdReportRoute
}

const AnalysisIdRouteChildren: AnalysisIdRouteChildren = {
  AnalysisIdReportRoute: AnalysisIdReportRoute,
}

const AnalysisIdRouteWithChildren = AnalysisIdRoute._addFileChildren(
  AnalysisIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountPendingRoute: AccountPendingRoute,
  AccountRejectedRoute: AccountRejectedRoute,
  AccountSuspendedRoute: AccountSuspendedRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  ReviewerRoute: ReviewerRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VendorRoute: VendorRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminStandardsRoute: AdminStandardsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AnalysisIdRoute: AnalysisIdRouteWithChildren,
  AnalysisNewRoute: AnalysisNewRoute,
  OfficerApplicationsRoute: OfficerApplicationsRoute,
  OfficerEvaluationRoute: OfficerEvaluationRoute,
  OfficerInspectionRoute: OfficerInspectionRoute,
  OfficerProcurementsRoute: OfficerProcurementsRoute,
  OfficerProfileRoute: OfficerProfileRoute,
  OfficerVendorsRoute: OfficerVendorsRoute,
  StandardsIdRoute: StandardsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  StandardsIndexRoute: StandardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
